### ISSUE TITLE
Scripts to pre-process raw-data

### ISSUE THREAD

**Issue by sameeravithana** [xptree/DeepInf#1]
Hello, I'm going to test your implementation using a custom dataset similar to Twitter. Do you have scripts to pre-process raw-data?

**Comment by jozerozero** [comment]
Yep, I also want to know how to pre-process the raw data, can you release these scripts ??

Thanks!

**Comment by LCorleone** [comment]
Yep, please release these scripts, thanks.

**Comment by xptree** [comment]
Thanks for your interest. The pre-processing procedure is introduced in section 4.1 of the DeepInf paper. We will consider releasing the pre-processing scripts later.

**Comment by littlesunCAICAI** [comment]
much pleasure to get the raw scripts for pre-processing

**Comment by mshahabi** [comment]
I have a question about the input data: I am wondering whether the last element of each row in the"vertex_id.npy" is the ID for ego node?

I am also curious whether you the data processing script is being released or not?

**Comment by littlesunCAICAI** [comment]
i also want to know it .you may find the wrong person.i don.t do this work for deepInf.if you get the scripts.please give me a copy.thanks a lot.



---Original---

**Comment by xptree** [comment]
Sorry for the delay. An example of preprocessing code can be found at https://github.com/xptree/DeepInf/tree/preprocess.

**Comment by littlesunCAICAI** [comment]
much appreciation




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xptree/DeepInf"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 中午11:12
收件人:&nbsp;"xptree/DeepInf"<DeepInf@noreply.github.com&gt;;
抄送:&nbsp;"START"<1613078403@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xptree/DeepInf] Scripts to pre-process raw-data (#1)





 
Closed #1.
