### ISSUE TITLE
关于多头Multi head Graph Attention计算的问题

### ISSUE THREAD

**Issue by carrie0307** [xptree/DeepInf#2]
您好：
    感谢您分享的代码，关于多头attention计算的部分有两处问题想请教，希望能得到您的回复:
    1. [Line84](https://github.com/xptree/DeepInf/blob/81c2412416d17dbf8d2e90d94b3b4d843838c9eb/src/gat_layers.py#L84)请问这一行的self.w是相当于paper中的参数c吗?
   2. [Line85,86,87](https://github.com/xptree/DeepInf/blob/81c2412416d17dbf8d2e90d94b3b4d843838c9eb/src/gat_layers.py#L85)中h_prime分别与self.a_src和self.a_dst相乘再相加，是对应paper中[Wh<sub>j</sub>||Wh<sub>i</sub>]的部分吗? 

 希望能得到您的回复，非常感谢！
祝好！

**Comment by xptree** [comment]
>> Line84请问这一行的self.w是相当于paper中的参数c吗?

self.w对应paper中的w。

>> Line85,86,87中h_prime分别与self.a_src和self.a_dst相乘再相加，是对应paper中[Whj||Whi]的部分吗?

论文中的c对应a_src和a_dst的拼接。
