### ISSUE TITLE
Ego node ID

### ISSUE THREAD

**Issue by mshahabi** [xptree/DeepInf#5]
I have a question about the input data: I am wondering whether the last element of each row in the"vertex_id.npy" is the ID for ego node?

I am also curious whether you the data processing script is being released or not?

**Comment by xptree** [comment]
Yes, whether the last element of each row in the"vertex_id.npy" is the ID for ego node?

You can find an example of preprocessing code at https://github.com/xptree/DeepInf/tree/preprocess.

**Comment by mshahabi** [comment]
Thanks alot.
